### ISSUE TITLE
Support webjobs

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#109]
Looks like many people want to run nsb in this new service

**Comment by SeanFeldman** [comment]
Have created a [demo project](http://bit.ly/nsb_webjob) to demonstrate how NSB can be used with Azure. This should be a good starting point for those that are interested.

**Comment by SeanFeldman** [comment]
Video Store [sample with WebJobs](http://bit.ly/nsb_webjobs_videostore)

**Comment by johnkattenhorn** [comment]
I'll be sure to take a look (I'd already got something working) to see your take on a webjob implementation and see if I can learn something.

**Comment by SeanFeldman** [comment]
Sample used InMemoryPersistence, which is not good for production. Requires a little more work.

**Comment by rogeclub** [comment]
Yves - when you say that there is no official support, does that just mean that we shouldn't be trying to attempt this for production systems, or does it just mean there is no simplified hosting story for WebJobs?

**Comment by johnkattenhorn** [comment]
I’ve had it running without any issues using a WebJob although it doesn’t handle a lot of throughput so not exactly stress tested.

The only issue I found was unrelated to NServiceBus, it was more deploying the WebJob into a running Azure WebSite which was a bit clunky.

**Comment by yvesgoeleven** [comment]
@rogeclub it means that we haven't fully tested the scenario yet, and that using it in production is at your own risk. There is no simplified hosting model either, but I don't expect that ever to exist as MS has announced so many different hosting models lately that it's going to be unfeasible for us to keep up with all of those. Going forward, self hosting will probably be the norm.

**Comment by SeanFeldman** [comment]
@yvesgoeleven can we close this one?
It's not officially supported, but it can be done.https://github.com/ParticularLabs/APIComparer is an example.

**Comment by SeanFeldman** [comment]
This is a self-hosted case.
