### ISSUE TITLE
Messages ending up in ASB Deadletter queue

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#238]
Noticed that a lot messages ends up in the ASB Deadletter queue after running up 10+ workers, some without any NSB Error. 

![image](https://cloud.githubusercontent.com/assets/641348/5680267/6b624752-983d-11e4-9832-f9f1c951e4d7.png)

**Comment by yvesgoeleven** [comment]
The max delivery count on your queue is probably to low, it should be 6x max number of instances

**Comment by danielHalan** [comment]
Ok... due that each worker might try the messages, with internal retry counters? Maybe should have a central storage for how many instances are running and then adjust the ASB "MaxDeliveryCount" accordingly.

**Comment by yvesgoeleven** [comment]
We are aware of this issue/inconvenience, and have a feature request open on the core that would allow the delegation of FLR (and other retry rules) to a specific transport. I don't have an eta on this yet, but it is on the planning. I assume upping the retry count resolved the issue for now and close the issue, if not feel free to reopen
