### ISSUE TITLE
Self-hosted Publisher not publishing events to ASB

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#239]
When Creating a self-hosted NSB Host, that is used to Publish Events, the Destination Queue seems to be missing, and no events are pushed to Azure. 

Get following Debug message on Publish (notice empty Queue Name)
```
2015-01-11 19:50:05.8136|DEBUG|NServiceBus.Unicast.Behaviors.DispatchMessageToTransportBehavior|Sending message Itq.xxxxxx.Domain.Events.System.CountriesAdded with ID c2285036-f0bc-4bf3-9924-a41d0146de82 to destination .
ToString() of the message yields: NServiceBus.Unicast.Messages.LogicalMessage
Message headers:
NServiceBus.MessageId:c2285036-f0bc-4bf3-9924-a41d0146de82, NServiceBus.CorrelationId:c2285036-f0bc-4bf3-9924-a41d0146de82, NServiceBus.OriginatingEndpoint:ItqAdmin, $.diagnostics.originating.hostid:20a1f8063fe258ce9924ac5d4fca6abf, NServiceBus.MessageIntent:Publish, NServiceBus.Version:4.6.8, NServiceBus.TimeSent:2015-01-11 12:50:05:655675 Z, NServiceBus.OriginatingMachine:ITQ-W03, NServiceBus.ContentType:application/json, NServiceBus.EnclosedMessageTypes:Itq.xxxxxx.Domain.Events.System.CountriesAdded, Itq.xxxxxx.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, WinIdName:, NServiceBus.ConversationId:95892044-081f-4ff2-9e5d-a41d0146de8c
```

The App.config contains following mapping

    <MessageEndpointMappings>
      <add Assembly="Itq.Legal.Domain" Namespace="Itq.Legal.Domain.Events.System" Endpoint="ItqXXX" />
     </UnicastBusConfig>

And using Feature,
```
      Configure.Features.Enable<StorageDrivenPublisher>();
```
And bus created with,
```
...
                .AzureSagaPersister()
                .AzureSubscriptionStorage()
                .UseAzureTimeoutPersister()
              .UnicastBus()
                .LoadMessageHandlers()
            .CreateBus()
            .Start(() => Configure.Instance.ForInstallationOn<NServiceBus.Installation.Environments.Windows>().Install());
```

**Comment by yvesgoeleven** [comment]
Storage Driven Publisher serves no purpose for ASB, it uses Topics internally. Destination queues & subscriptions are never automatically created (intentionally), the receiving endpoint should create it instead

**Comment by danielHalan** [comment]
Ok, the purpose of the configuration above was to mimic a working NSB.Host AsA_Publisher configuration. What is needed in terms of configuration for the self-hosted Bus to be able to publish events (Bus.Publish()) to ASB?

**Comment by yvesgoeleven** [comment]
It's controlled by MessageDrivenSubscriptions feature from the core, which is always turned on by the ASB transport, so you shouldn't have to do anything

**Comment by danielHalan** [comment]
Ok, 
a) does "Sending message xxx with ID yyy to destination ." have any indication on what can be astray?
b) where should one start tracing to figure out why Events are not being sent to Azure?

**Comment by yvesgoeleven** [comment]
The message should be sent to the topic named nameofpublisher.events and there should be a subscription on that topic with the name "nameofsubscribedendpoint.subscribedtype". If the latter misses you may have to check the messageendpointmappings of the subscriber (this determines where is subscribed to)

**Comment by danielHalan** [comment]
yes, the topic & subscription's are there, (as exact same Publisher exists as NSB.Host.exe, which publishing is working correctly).
The Question is, where to look in the self hosted Bus, why its not storing the message inside the "nameofsubscribedendpoint.subscribedtype"

**Comment by yvesgoeleven** [comment]
First thing I do is add a debug subscription to the topic, whether to see if the message is actually not delivered, or it is but the receiver sallows it. If that confirms that the message is not being sent to the topic, then only thing left to do is attach debugger.

AzureServiceBusTopicPublisher should be the one publishing, so placing a breakpoint there should give a good starting point. If that doesn't hit, you could try adding a breakpoint to DispatchMessageToTransportBehavior from the core source and trace from there...

**Comment by danielHalan** [comment]
Found the issue, it uses the NSB.EndpointName to find the Topic, (<nsb.name>.Topics), was hoping that the MessageEndpointMappings would be used for figuring out which Events will be sent from which Queue, 

<add Assembly="Itq.xxx.Domain" Namespace="Itq.Legal.xxx.Events.A" Endpoint="ItqCH..." />
<add Assembly="Itq.xxx.Domain" Namespace="Itq.Legal.xxx.Events.B" Endpoint="ItqCH..." />
