### ISSUE TITLE
Azure Saga Persister - DateTimeOffset exception

### ISSUE THREAD

**Issue by jhashemi** [Particular/NServiceBus.Azure#246]
else if (propertyInfo.PropertyType == typeof(DateTimeOffset))
                    {
                        var dateTimeOffset = entity[propertyInfo.Name].DateTimeOffsetValue;
                        propertyInfo.SetValue(toCreate, dateTimeOffset.HasValue ? dateTimeOffset.Value : default(DateTimeOffset), null);
                    }

needs to be added. getting the "not supported by azure table storage" error.

**Comment by SeanFeldman** [comment]
Hi @jhashemi,

Azure table storage services has a limit on supported types outlined in [MSDN documentation](https://msdn.microsoft.com/library/azure/dd179338.aspx). `DateTimeOffset` is unfortunately not supported. You could store it as a string and convert back.
