### ISSUE TITLE
When using Microsoft.Data.Services.Client version 5.6.3 a ReflectionTypeLoadException occures

### ISSUE THREAD

**Issue by sanderdriesen** [Particular/NServiceBus.Azure#247]
After updating the Microsoft.Data.Services.Client package to 5.6.3 a ReflectionTypeLoadException is occurred when the assembly scanner tries to fetch the types from the NServiceBus.Azure assembly. NServiceBus.Azure is expecting the 5.6.0 version. On local development machines is works fine because the 5.6.0 version is probably installed as part of the Azure SDK, but as soon you deploy to production like environments you receive the following exception:

2015-02-12 09:43:50,638 [10] WARN  NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver - Failed to fetch timeouts from the timeout storage
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object obj) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPersisterReceiver.cs:line 88
   at System.Threading.Tasks.Task.Execute()

At that point it is not clear what causes this exception. 
See also my full investigation on stackoverflow: http://stackoverflow.com/questions/28473442/nservicebus-5-using-azurestoragepersistence-results-in-failed-to-fetch-timeouts

Adding a binding redirect in the app.config does not have any effect. The NServiceBus.Azure package seems to support Microsoft.Data.Services.Client versions >= 5.6.0.0 < 6.0.0.0, but unfortunately it isn't ;)

Can you make the NServiceBus.Azure compatible with Micosoft.Data.Services.Client 5.6.3?

**Comment by yvesgoeleven** [comment]
Answered on the SO question, imo binding redirect should work, but it's range is specified wrongly

**Comment by sanderdriesen** [comment]
@SeanFeldman I tried the by visual studio added default range after updating the package, end of the range was 5.6.3.0. Did not try the end range 6.0.0.0 as @yvesgoeleven suggested yet. I will give that a try and keep you posted.

**Comment by yvesgoeleven** [comment]
@sanderdriesen your range should have worked as well, just be sure that the target version is the one of the assembly on your disk (use reflector or dotpeek to validate inside the assembly)

If that doesn't work, there is a tool called fuslogvw.exe inside the .net framework folders, C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1a\bin\NETFX 4.5.1 Tools\, or similar depending on your machine & installation. You can use that tool to see for which version & where .net is search for an assembly at runtime.

**Comment by sanderdriesen** [comment]
Hi @yvesgoeleven, I used ILSpy to extract the following information from the Microsoft.Data.Services.Client.dll located in the bin folder.

[assembly: AssemblyVersion("5.6.3.0")]
[assembly: AssemblyFileVersion("5.6.3.62017")]
[assembly: AssemblyInformationalVersion("5.6.3.62017")]
[assembly: SatelliteContractVersion("5.6.3.0")]

I also added more logging in the NServiceBus.Core AssemblyScanner to get the exact error under the hood:
![image](https://cloud.githubusercontent.com/assets/7438361/6324250/c136dc3e-bb37-11e4-9554-dfa9d7ef78cd.png)

The assembly redirects in my app.config are:
<dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.0.1" newVersion="3.1.0.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>

When I add the binding redirects in a new created NServiceBus.Host.exe.config it is working with the 5.6.3 version. Is it supposed to work like that, creating a NServiceBus.Host.exe.config instead of defining the binding redirects in my app.config?

**Comment by yvesgoeleven** [comment]
Hmm I see, pretty annoying, but indeed possible that you need to specify it in the host config.

The reason is that default load behavior of the CLR is at the process level, which includes the host config, once the host is loaded we actively switch over to the appdomain level (using topshelf) from then on it uses the endpoint's config...

But if the CLR needs to resolve the reference prior to the switch to the appdomain, you will have to put the redirect at the host level (and at the endpoint level I guess)

I'm happy to see you got it resolved

**Comment by sanderdriesen** [comment]
Thanks for your help!
