### ISSUE TITLE
Update nuspecs to WindowsAzure.Servicebus 2.6 and WindowsAzure.Storage 4.3

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Azure#256]
Nuspec files for nuget packages has outdated versions of dependencies forcing customers to manually execute update-package.

**Comment by yvesgoeleven** [comment]
raising the lower bound also forces people to update, even if they don't want to and it's not needed
 We got quite a lot of feedback in the past to stop doing this.

The real issue in in nuget not allowing you to choose your prefered update policy, right now it always gives you the newest minor in the oldest major version.

Next nuget (in VS2015) allows you to set the policy and then this issue will go away
