### ISSUE TITLE
TraceLogger directive in 6.2+

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#259]
NSB 5.2 with NSB.Azure 6.2.1 is raising a Obsolete Error when using TraceLogger, what is the directive to disable / enable TraceLogger?

``
'NServiceBus.SetLoggingLibraryForAzure.TraceLogger(NServiceBus.BusConfiguration)' is obsolete: 'Trace logging is now built into the core of NSB. Will be removed in version 7.0.0.'	
``

Also the doc page would need some updating in "Cloud Services - Web Roles" section,
http://docs.particular.net/nservicebus/azure/hosting-in-azure-cloud-services

**Comment by yvesgoeleven** [comment]
The default logger already logs to trace now (among other things), so this one just isn't needed anymore. Indeed, doco needs update, will take care of it

**Comment by danielHalan** [comment]
Ok, is there a way to disable TraceLogger in situations one want only to use local NLogging? (without changing the .config that is)

**Comment by yvesgoeleven** [comment]
I think all you need to do is set the NLogFactory, that will disable the default http://docs.particular.net/nservicebus/logging/

**Comment by danielHalan** [comment]
Ok thanks for quick answer, so all logging is now thru Core, nice.
