### ISSUE TITLE
Saga ReplyToOriginator not working

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#262]
After upgrading from NSB 4.8 and Azure 5.x,

Saga ReplyToOriginator is no longer replying to the originator.

I have re-created the scenario based on a NSB Sample project that use CommandHandler => Return (which works as expected), I've added a "SomeSaga" that should return a Message back to Web Client.

http://halan.blob.core.windows.net/debug/NSB5_SagaReplyIssueR1.zip

Noted, the returning message ends up in the "error" queue, saying it can't find any handler for the type.
```
No handlers could be found for message type: NSB.Test.Commands.SagaResult
System.InvalidOperationException: No handlers could be found for message type: NSB.Test.Commands.SagaResult
```

**Comment by danielHalan** [comment]
A good question is why the hosted NSB is throwing a "no handler found" exception, as the handler exists on remote host (web) specified in the message header, which was supported in NSB4.x ReplyToOriginator() ... any changes in regard to this?

**Comment by yvesgoeleven** [comment]
Going to close this issue and track it over here https://github.com/Particular/NServiceBus/issues/2748
