### ISSUE TITLE
ISagaFinder Data-Context for Azure Storage 

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#263]
Can't seem to find any reference to what Context is used for retrieving the Data object in ISagaFinder, when using AzureStorage / AzureServiceBus. 

The only reference I could find is the AzureServiceBus acceptance testing for ISagaFinder, but no storage context is used https://github.com/Particular/NServiceBus.AzureServiceBus/blob/3515d5444084c6a4c074c70ba5fb250aacd6a6e6/src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.5.2.2/Sagas/When_a_finder_exists.cs

**Comment by yvesgoeleven** [comment]
Context is only relevant for transactional storages, in combination with outbox functionality, so that they can share their connection. It makes no sense for storage as storage is non transactional and per request anyway. Today this construct is only supported for sql azure (or in memory) as a persister in azure, in the future ServiceFabric may be added to that list.

**Comment by yvesgoeleven** [comment]
PS: the context that you are referring to is part of our acceptence testing framework, and has nothing to do with data context

**Comment by yvesgoeleven** [comment]
Feel free to reopen if I misunderstood your question btw (not sure)

**Comment by danielHalan** [comment]
Ok, was thinking in regard to simplifying the access to (Saga) Storage, and abstract NSB.Azure specific solutions (ie. Table names). 

But yes, it's just a nice-to-have feature :)

**Comment by danielHalan** [comment]
also the question was in regard if there was anything equivalent to other storage engines, as in all available samples show injection of data-Context, maybe could add a Azure sample just to clarify the current solution. 
http://docs.particular.net/samples/saga

**Comment by yvesgoeleven** [comment]
There is nothing equivalant, azure storage is extremely limited when it comes to searching/finding, if you have advanced needs in that regard I suggest to look into other persisters
