### ISSUE TITLE
"Queue empty" Error

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.Azure#264]
Hi, 

After upgrading to 6.x, during debug session a new exception is intercepted quite frequently, 

```
Fatal|NServiceBus|Failed to receive message from Azure ServiceBus.
System.InvalidOperationException: Queue empty.
   at System.Collections.Queue.Dequeue()
   at System.Collections.Queue.SynchronizedQueue.Dequeue()
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusDequeueStrategy.TryProcessMessage(Object obj) in c:\BuildAgent\work\2f57832e2eee436e\src\Transport\Receiving\AzureServiceBusDequeueStrategy.cs:line 108
   at System.Threading.Tasks.Task.Execute()
```

**Comment by yvesgoeleven** [comment]
Strange, Haven't see this yet. What's the impact on the running application?

**Comment by danielHalan** [comment]
Haven't associated it with any impact on functionality, currently most annoyance during debugging.

**Comment by yvesgoeleven** [comment]
I notice the stacktrace mentions the SynchronizedQueue, we stopped using that in 6.2 in favor of a blocking collection, so I assume you're on 6.1? Can you try upgrading and see if it goes away?

**Comment by danielHalan** [comment]
Actually I'm on 6.2.1

![image](https://cloud.githubusercontent.com/assets/641348/8326435/730af302-1a8b-11e5-967d-6f7d6a5cc9dd.png)

**Comment by yvesgoeleven** [comment]
Strange, I'll have to look into it deeper and try to reproduce

**Comment by yvesgoeleven** [comment]
6.2.1 still has the synchronized queue it seems, 6.2.2 and up will have the blocking collection, maybe worth trying to upgrade

**Comment by danielHalan** [comment]
Which package, NSB.Azure latest is 6.2.1 (https://www.nuget.org/packages/NServiceBus.Azure)

See 6.3 of Transport, something interesting?
https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureServiceBus

**Comment by yvesgoeleven** [comment]
nsb.azure and nsb.azure.transports.windowsazureservicebus are now decoupled in version, you want to try by updating the windows azure servicebus one

**Comment by yvesgoeleven** [comment]
@danielHalan what's the status on this one, did you see the error again after upgrading?

**Comment by danielHalan** [comment]
After updating to latest version. haven't re-occurred.
