### ISSUE TITLE
Azure Storage Persistence - mixed statics and non-statics

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Azure#277]
## Who's affected

* Anyone who's using Azure Storage Persistence in a multi-hosted scenario

## Symptoms

Overriding table name for persisting subscriptions in a multi-hosted scenario can cause records be stored in the wrong tables. Table name is a static, but each endpoint is using an instance of subscription persister.

## Workaround

Keep all endpoint subscriptions in the same table (`Subscriptions` is the default name).

Desk Case: [17651](https://nservicebus.desk.com/agent/case/17651)

**Comment by SeanFeldman** [comment]
The troubling code is [here](https://github.com/Particular/NServiceBus.Azure/blob/b55cc9de8498b2c797a0f6b65f4c72bc007030a3/src/NServiceBus.Azure/Subscriptions/Azure/SubscriptionServiceContext.cs#L33)

When each endpoint is setting up the persistence for subscriptions, it [changes the static directly](https://github.com/Particular/NServiceBus.Azure/blob/b55cc9de8498b2c797a0f6b65f4c72bc007030a3/src/NServiceBus.Azure/Subscriptions/Azure/AzureStorageSubscriptionPersistence.cs#L28) which will cause an issue in multi-hosted scenario.

**Comment by SeanFeldman** [comment]
In order to fix this, this will be affecting public API. @Particular/azure-maintainers any thoughts?

**Comment by mauroservienti** [comment]
Is multi hosting done using appDomains? If not introducing an appDomain per hosted bus should solve this since statics in .Net are per-appDomain.

**Comment by SeanFeldman** [comment]
@mauroservienti multi-hosting done the folloing way (same appdomain): docs.particular.net/samples/hosting/multi-hosting/

**Comment by mauroservienti** [comment]
As said introducing an appDomain per bus instance should fix this without changing the public API, I should have a working sample somewhere.

**Comment by SeanFeldman** [comment]
@mauroservienti that could be added as a workaround, indeed.

**Comment by Scooletz** [comment]
How about introducing 'ConditionalWeakTable<AzureSubscriptionStorage, BagOfNeededValues>' ? There's an `AzureSubscriptionStorage` instance created in there. If we provided a method for registering a bag of values in `SubscriptionServiceContext` and retrieving it by an `AzureSubscriptionStorage` instance that would be a nice API without leaking resources as well.

**Comment by SeanFeldman** [comment]
@Scooletz how that would address those static properties that are public and accessible?

**Comment by Scooletz** [comment]
I've checked the code. My take would be to move all the creating/ensuring code to the `AzureStorageSubscriptionPersistence.Setup()` The rest of usages is in the 'AzureSubscriptionStorage' which is again, created by the `AzureStorageSubscriptionPersistence`. One doesn't need the CWT I mentioned before. I should've taken a better look before discussing this.
It doesn't look big.

**Comment by SeanFeldman** [comment]
That's what @dbelcham and myself have discussed already. The caveat is to obsolete public statics in case those are used directly.

**Comment by SeanFeldman** [comment]
Closing this as there is a workaround and issue is going to be addressed in the next major release.
