### ISSUE TITLE
Completed saga does not remove secondary index record

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Azure#283]
## Who's affected

* Any user using NServiceBus.Azure persistence for sagas version 6.4.0

## Symptoms

When saga completes, secondary index record is left behind, filling up storage table with records.

## Steps to reproduce

Start and complete a saga. Once saga completed, inspect storage table to find secondary index record. [Persistence sample](http://docs.particular.net/samples/azure/storage-persistence/) can be used to reproduce the issue.

**Comment by SeanFeldman** [comment]
[`Complete()` operation](https://github.com/Particular/NServiceBus.Azure/blob/3bb9d0fb54c18fb12e30b7bebb72fc8be7d4af97/src/NServiceBus.Azure/SagaPersisters/Azure/AzureSagaPersister.cs#L178) doesn't remove the secondary index.

**Comment by Scooletz** [comment]
Let's keep the discussion under ASP https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/74
