### ISSUE TITLE
Typo in a string when installing NServiceBus.Azure on net standard class library

### ISSUE THREAD

**Issue by mishra14** [Particular/NServiceBus.Azure#294]
Found a typo while installing NServiceBus.Azure on class library targeting netstandard 

`Replace NServiceBus.Azure packages with appropreate ones as described in README.MD at https://github.com/Particular/NServiceBus.Azure
`

Actual - appropreate
Expected - appropriate

**Comment by SeanFeldman** [comment]
Thank you @mishra14. Good catch 😃 

The repository is deprecated now and there's no real value to release an update package as it will add more confusion. We've documented [here](https://github.com/Particular/NServiceBus.Azure/blob/develop/README.md) the changes. Deprecation package is for users to know that `NServiceBus.Azure` is no longer a package they need to reference. As well as what packages should be referenced instead.
