### ISSUE TITLE
Review version policy WindowsAzure.ServiceBus

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#298]
Current: Fixed Major Range

Used in 
- NServiceBus.Azure.Transports.WindowsAzureServiceBus: Range [4.0.0, 5.0.0)

**Comment by yvesgoeleven** [comment]
My suggestion, leave it as is

**Comment by SeanFeldman** [comment]
ASB team is following SemVer. So the range is good for us.

**Comment by boblangley** [comment]
Agreed, Fixed Major Range 👍

**Comment by Scooletz** [comment]
👍

**Comment by danielmarbach** [comment]
👍

**Comment by yvesgoeleven** [comment]
As we all agree here, let's leave it as is
