### ISSUE TITLE
Review version policy Microsoft.ServiceFabric.Data

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#301]
Current: Fixed Minor Range

Used in 
- NServiceBus.Persistence.ServiceFabric: Range [2.5.0, 3.0.0)

**Comment by yvesgoeleven** [comment]
Suggestion: Keep as is

**Comment by boblangley** [comment]
Agreed 👍

**Comment by Scooletz** [comment]
👍

**Comment by danielmarbach** [comment]
Agreed

**Comment by yvesgoeleven** [comment]
As we all agree here, let's leave it as is
