### ISSUE TITLE
Create a sample showing integration with azure monitoring tools

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#305]
Connects to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/100

Similar to https://github.com/Particular/LaunchWave.DevOpsAdvancedMonitoring/issues/88, but using azure monitoring

**Comment by SeanFeldman** [comment]
Should the issue be raised under LaunchWave.DevOpsAdvancedMonitoring @yvesgoeleven ?

**Comment by yvesgoeleven** [comment]
@Particular/launchwave-devopsadvancedmonitoring-squad where does this belong?

**Comment by mikeminutillo** [comment]
@yvesgoeleven if you want us to drive it, please raise it in the launch wave repo

**Comment by yvesgoeleven** [comment]
@mikeminutillo perfect. You drive it in terms of timing etc, we'll help with the implementation.

**Comment by SeanFeldman** [comment]
This was opened recently with (I'm assuming) assumption that work will be done. Looks like plans have changed. @yvesgoeleven ?

**Comment by SeanFeldman** [comment]
Done. We've got a [sample for AppInsights](https://docs.particular.net/samples/application-insights).
