### ISSUE TITLE
Release template

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#307]
I haven't seen it anywhere else, so if this covered by any other maintainer group, I'd be grateful if you could point to the resources.

When we work on deployments, we don't really have a template per se. Yes, we have detailed notes on branching and Git, somewhat of a write-up about deployment process in general, have a paragraph on updating latest supported versions script, manual announcement creation (not documented), smoke testing. And perhaps more.

What I find effective is a break down of what needs to be done. Not only it helps to ensure not a single step is missed, but also allows verification and quick tracking what's at what stage. Example: PoA for PlatDev issue #1308.

Source: https://particularsoftware.slack.com/files/sean.feldman/F5UF9TZB2/Releasing_-_for_discussion

**Comment by SeanFeldman** [comment]
I'd add to the list as a prerequisite to review supported versions (and even re-run the script to ensure it's up-to-date) to avoid planning to patch versions that just recently came out of support.

**Comment by SeanFeldman** [comment]
Captured [here](https://github.com/Particular/NServiceBus.Azure/blob/develop/templates/releasing-checklist.md)
