### ISSUE TITLE
Smoketest samples

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#308]
From @SimonCropp 

@azure-maintainers i updated the cloud showcase to NServiceBus.Azure.Transports.WindowsAzureStorageQueues.7.3.0 and Microsoft.WindowsAzure.Storage.8.1.4.0 and Newtonsoft.Json.10.0.3 and NServiceBus.Persistence.AzureStorage.1.4.0  you may want to smoke test

**Comment by yvesgoeleven** [comment]
Sample no longer works, it throws Could not load type 'NServiceBus.Configuration.AdvanceExtensibility.AdvanceExtensibilityExtensions' from assembly 'NServiceBus.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'

**Comment by SimonCropp** [comment]
@yvesgoeleven thats weird. that sample should not be v7 yet??

**Comment by yvesgoeleven** [comment]
@SimonCropp yeah for some reason it is ported to 7. Now testing v6 one

**Comment by yvesgoeleven** [comment]
v6 version doesn't work either, I'll investigate

**Comment by yvesgoeleven** [comment]
v6 version works fine, issue was related to my local storage emulator.

**Comment by SeanFeldman** [comment]
ASQ (uses storage) sample is broken. 
Persistence sample might be broken as well.
Reopening.

**Comment by SeanFeldman** [comment]
#311 to address the rest of samples

**Comment by yvesgoeleven** [comment]
@SeanFeldman I smoketested them earlier this week, they worked fine. I'll double check if you like
