### ISSUE TITLE
Samples using Azure Storage require binding redirect update

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Azure#311]
When Azure showcase was updated, the rest of sample that rely on Storage did not got smoke tested and binding redirects might be invalid. Issue #308 was raised, but it didn't address all samples.

```
updated the cloud showcase to NServiceBus.Azure.Transports.WindowsAzureStorageQueues.7.3.0 and Microsoft.WindowsAzure.Storage.8.1.4.0 and Newtonsoft.Json.10.0.3 and NServiceBus.Persistence.AzureStorage.1.4.0 you may want to smoke test
```

- ASQ sample is broken.
- Persistence sample might be broken as well.

**Comment by SeanFeldman** [comment]
@yvesgoeleven haven't you worked on updating the samples already?

**Comment by yvesgoeleven** [comment]
@SeanFeldman I smoketested them earlier this week yes, they worked fine including the showcase, did I forget any?

**Comment by yvesgoeleven** [comment]
@SeanFeldman looks like @SimonCropp updated to 8.2.1 a d ay after I performed the smoke tests for 8.2.0, the ASQ sample is indeed broken now because of wrong binding redirect. 

I'll fix it, but we need to redo all the smoketests and figure out a better way to stay in sync. It takes a few hours to open/compile/run all the samples, it is impossible to keep up this way (and work on TFs, squads etc at the same time)

**Comment by SimonCropp** [comment]
u dont need to smoke test all of them. just one will do

**Comment by yvesgoeleven** [comment]
PR: https://github.com/Particular/docs.particular.net/pull/3011

**Comment by yvesgoeleven** [comment]
@SimonCropp but then we won't be able to prevent some samples from not working, like this one, is that acceptable?

**Comment by SimonCropp** [comment]
the binding redirect issue should be fixable with a search and replace. then smoke test on to confirm the change

**Comment by yvesgoeleven** [comment]
> with a search and replace

what tool can do that?

**Comment by SimonCropp** [comment]
any text editor

**Comment by SeanFeldman** [comment]
Any tool won't work - notepad won't do it with multiple files 😉

I found VS code very handy with that.
