### ISSUE TITLE
NServiceBusRoleEntrypoint constructor throwing System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by paddygreens** [Particular/NServiceBus.Azure#312]
Hi,

I am using  below versions on NService Bus
NServiceBus" version="6.1.2" 
 "NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.1.4" 
"NServiceBus.CastleWindsor" version="6.0.0" 
NServiceBus.Hosting.Azure" version="7.0.2" 
NServiceBus.Hosting.Azure.HostProcess" version="7.0.2" 

And the NServiceBusRoleEntrypoint constructor throwing System.Reflection.TargetInvocationException: 
```
System.Reflection.TargetInvocationException occurred
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)

Inner Exception 1:
RoleEnvironmentException: error
```

**Comment by SimonCropp** [comment]
@paddygreens is there no more information in the inner exception? and can you reproduce this when debugging on your local machine?

**Comment by paddygreens** [comment]
There is no information other than this.  This is happening in the local
machine itself.

**Comment by SeanFeldman** [comment]
@paddygreens is it a sample you're trying to run? Would be nice if you could share with us a repro to try out.

**Comment by paddygreens** [comment]
not a  sample. I guess it's not compatible with one of the libraries i would have installed for logging purpose. Created a new repo with a fresh setup without those libraries fixed it. However the exception needs to be more descriptive in order to figure out the actual cause.
