### ISSUE TITLE
Smoketest samples

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#313]
Some package refs got updated, https://github.com/Particular/docs.particular.net/commit/a1c1bbeacfe441aa7f848186af4162e10060fb94 needs smoketesting

**Comment by SimonCropp** [comment]
also  WindowsAzure.ServiceBus.4.1.3 https://github.com/Particular/docs.particular.net/commit/432d0587c5a057e72c1dbc5ee94a923113a0611d

**Comment by SeanFeldman** [comment]
It didn't have a single change for ASB. Just saying.

**Comment by yvesgoeleven** [comment]
All samples tested worked fine
