### ISSUE TITLE
Ship installation scripts as part of the transport nugets

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#314]
Similar https://github.com/Particular/PlatformDevelopment/issues/1416 for each transport

Todo: create issue for each transport

**Comment by indualagarsamy** [comment]
@yvesgoeleven - Since PlatDev is a private repo, do you want to add a little bit more into the issue description?

**Comment by yvesgoeleven** [comment]
Closed in favor of:

https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/283
https://github.com/Particular/NServiceBus.AzureServiceBus/issues/651
