### ISSUE TITLE
Add support for new Azure Servicebus High Availability features

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Azure#37]
Raised by @yvesgoeleven
Migrated from by https://github.com/Particular/NServiceBus/issues/1376

Paired Namespaces can now be used to support high availability of namespaces into the azure servicebus transport, see http://msdn.microsoft.com/en-us/library/dn292562.aspx for more details.

**Comment by yvesgoeleven** [comment]
Migrated to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/2
